services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: credixo
      POSTGRES_PASSWORD: credixo
      POSTGRES_DB: credixo_db
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://credixo:credixo@db:5432/credixo_db
